# Generated by Django 5.1.4 on 2025-04-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_customuser_phone_number_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='incidents/audio/'),
        ),
    ]
