# Generated by Django 5.1.4 on 2025-04-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='incidents/audio/'),
        ),
    ]
